# Generated by Django 6.0.8 on 2026-10-02 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('endpoint_host', models.CharField(help_text='Public IP or hostname clients connect to, e.g. 103.164.54.159', max_length=255, verbose_name='Public endpoint')),
                ('listen_port', models.PositiveIntegerField(default=51820)),
                ('interface', models.CharField(default='wg0', max_length=15)),
                ('config_path', models.CharField(default='/etc/wireguard/wg0.conf', max_length=255)),
                ('public_key', models.CharField(blank=True, help_text="Filled automatically by 'Import from server'.", max_length=64, verbose_name='Server public key')),
                ('server_address', models.CharField(default='10.7.0.1/24', help_text="Server tunnel address(es), e.g. '10.7.0.1/24' or '10.7.0.1/24, fddd:2c4:2c4:2c4::1/64'", max_length=128)),
                ('dns', models.CharField(blank=True, default='1.1.1.1', max_length=128, verbose_name='Client DNS')),
                ('client_allowed_ips', models.CharField(default='0.0.0.0/0, ::/0', help_text='0.0.0.0/0, ::/0 = full tunnel (all traffic through the VPN).', max_length=255, verbose_name='Client AllowedIPs')),
                ('persistent_keepalive', models.PositiveIntegerField(default=25)),
                ('mtu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Client MTU')),
                ('connection', models.CharField(choices=[('ssh', 'SSH (manage a remote Linux server)'), ('local', 'Local (this app runs on the VPN server itself)')], default='ssh', max_length=8)),
                ('ssh_host', models.CharField(blank=True, max_length=255, verbose_name='SSH host')),
                ('ssh_port', models.PositiveIntegerField(default=22, verbose_name='SSH port')),
                ('ssh_user', models.CharField(blank=True, default='root', max_length=64, verbose_name='SSH user')),
                ('ssh_key_path', models.CharField(blank=True, help_text='Recommended. e.g. C:\\Users\\you\\.ssh\\id_ed25519', max_length=500, verbose_name='SSH private key file')),
                ('ssh_password', models.CharField(blank=True, help_text='Only if you do not use a key. Stored in the local database.', max_length=255, verbose_name='SSH password')),
                ('use_sudo', models.BooleanField(default=False, help_text='Tick when the SSH user is not root (needs passwordless sudo).')),
                ('client_conf_dir', models.CharField(blank=True, default='/root', help_text='Where wireguard-install saved client .conf files (used to recover keys on import).', max_length=255)),
                ('auto_apply', models.BooleanField(default=True, help_text='Push peer changes to the server immediately after every edit.')),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=32)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Disabled automatically after this.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('private_key', models.CharField(blank=True, max_length=64)),
                ('public_key', models.CharField(max_length=64)),
                ('preshared_key', models.CharField(blank=True, max_length=64)),
                ('imported', models.BooleanField(default=False)),
                ('last_handshake', models.DateTimeField(blank=True, null=True)),
                ('last_endpoint', models.CharField(blank=True, max_length=128)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Account allowed to see and download this config.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_clients', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='vpn.server')),
            ],
            options={
                'ordering': ['server__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('server', 'name'), name='unique_client_name_per_server'), models.UniqueConstraint(fields=('server', 'ipv4'), name='unique_client_ip_per_server'), models.UniqueConstraint(fields=('server', 'public_key'), name='unique_client_key_per_server')],
            },
        ),
    ]
