# Generated by Django 6.0.8 on 2026-10-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='client_conf_dir',
            field=models.CharField(blank=True, default='/root', help_text='SSH mode only: where wireguard-install saved client .conf files (used to recover keys on import). Local mode uses CLIENT_DIRS in the helper script.', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='config_path',
            field=models.CharField(default='/etc/wireguard/wg0.conf', help_text='SSH mode only. Local mode always uses /etc/wireguard/<interface>.conf.', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='connection',
            field=models.CharField(choices=[('local', 'Local (this app runs on the VPN server itself)'), ('ssh', 'SSH (manage a remote Linux server)')], default='local', max_length=8),
        ),
    ]
